# Site settings
title: Pemba Rinzi Sherpa
name: Pemba Rinzi Sherpa

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/pemba007
 - title: StackOverflow
   url: https://stackoverflow.com/users/11363566/pemba-sherpa
 - title: LinkedIn
   url: https://www.linkedin.com/in/pemba-sherpa-88760114a/
 - title: Quora
   url: https://www.quora.com/profile/Pemba-Rinzi-Sherpa

#Any buzzword skills you want to include
skills:
 - HTML
 - CSS
 - SSH
 - JavaScript
 - ReactJS
 - API design
 - ElectronJS
 - PHP
 - WordPress
 - Sequelize
 - Redux
 - Saga
 - SQL
 - REST

# #Blogfeed is optional - including this will add JS to call the feed and populate blog list
# blogfeed: https://automateddeveloper.blogspot.com/feeds/posts/default?alt=json

#Work experience is required
roles:
 - title: DevOps
   start: 2018
   end: 2019
   employer: The Delta Labs Pvt Ltd.
#    description: Legaltech startup producing a range of innovative legal products. Products include <a href="https://www.juriosity.com" taget="_blank">Juriosity</a>, <a href="https://www.fromcounsel.com" taget="_blank">FromCounsel</a>, <a href="https://www.sparqa.com" taget="_blank">Sparqa</a>.
 - title: JavaScript Intern
   start: 2018
   end: 2018
   employer: TechDurbar
#    description: Emerald Street Ventures was established as an incubator vehicle for the development of a number of software and legal-tech projects, and a rapidly growing, London-based start-up using innovative technologies to revolutionise and change the software and legal-tech landscape. Working with a range of cutting edge technologies and techniques including Scala, Cassandra, CoreOS, a variety of Machine Learning techniques.

#Education is required
education:
 - level: Bachelor of Science (B.Sc.)
   date: 2015
   subject: Computer Science and Information Technology
   school: Tribhuvan University

#This section is optional (as is the image link below)
# coursera:
#    profileurl: https://www.coursera.org/user/i/c6362b4056f755a04bef6a791a62102b
#    courses:
#     - title: Functional Programming Principles in Scala
#       link: https://www.coursera.org/course/progfun
#       optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/progfun/small-icon.hover.png
#       date: September 16, 2013
#     - title: Algorithms Design and Analysis, Part 1
#       link: https://www.coursera.org/specializations/algorithms
#       optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/algo/small-icon.hover.png
#       date: April 28, 2014

#This section is optional - embeds slideshows from speakerdeck
# to get the speakerdeck ID copy the embed code and look for the data-it attribute
# speakerdeck:
#    profileurl: https://speakerdeck.com/robhinds
#    talks:
#     - title: Product Management for Engineers
#       speakerdeckId: 94f0070c4e434ec79fe9b4eb2cb574e0
#       conference: API Conference, Berlin 2018
#     - title: Agile Machine Learning - from Theory to Production
#       speakerdeckId: ec84f2f56e9743afb0675b1eeeb6b6ce
#       conference: W-JAX Conference, Munich 2017 (London 2017)

#List of interesting Github repo/projects to include - optional
# github:
#  - robhinds/robhinds.github.io
#  - robhinds/ScaLambda
#  - robhinds/opinionated-akka-http
#  - robhinds/food2vec
#  - robhinds/microservices
#  - robhinds/spring-social-geeklist
#  - robhinds/spring-social-stackoverflow
#  - robhinds/genotype
#  - robhinds/footweets
#  - robhinds/ElasticSearchGradle

# #Stackoverflow flair is optional
# stackoverflow:
#    profileurl: http://stackoverflow.com/users/258813/rhinds
#    flairimageurl: http://stackoverflow.com/users/flair/258813.png

intro: |
 I am a computer science graduate currently working in technology. I primarily have experience working as a front-end developer but have worked across a broad range of tenchologies: NodeJs, ElectronJs and also 
 AngularJs. As well as a considerable amount of experience on Amazon Web Service(AWS).
 <br/><br/>
 I enjoy building a simple yet powerful codes. I believe good codes are those that are simple to understand yet powerful enough to do complexe tasks.
 
  
#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
#   <strong>Scala</strong>: My current role uses Scala as the primary language and have been building applications in Scala for the last two years. I am familiar with a range of Scala libraries, such as <a target="_blank" href="http://automateddeveloper.blogspot.com/2017/12/an-opinionated-guide-to-building-apis.html"> Akka-Http for building microservices</a> and <a target="_blank" href="http://automateddeveloper.blogspot.com/2018/09/generic-programming-with-scala.html"> Shapeless for generic programming</a>, as well as familiar with a range of <a target="_blank" href="https://basementcrowd.com/2018/11/28/scala-the-aux-pattern-path-dependent-types/" >functional programming techniques available</a>.<br/><br/>
#   <strong>Java</strong>: I am experienced in a variety of Java API’s and frameworks. I have worked with Spring 4, Spring Boot, JPA (Hibernate and EclipseLink) in addition to others. <br/><br/>
#   <strong>Groovy</strong> I have used Groovy as a language in production for ~4 years and I am familiar with many of the languages features (such as writing <a target='_blank' href="https://dzone.com/articles/functional-programming-groovy">Functional Programming style groovy</a>) and quirks (such as <a target="_blank" href="https://dzone.com/articles/groovy-retrospective-an-addendum-memory-usage-perm">memory leak issues</a>). <br/><br/>
#   <strong>Cloud platforms</strong>: I have primarily used AWS for running production apps on the cloud. I have experience setting up, configuring and running applications using a range of AWS offerings, including EC2, RDS, S3, Cogito, <a target="_blank" href="http://automateddeveloper.blogspot.com/2018/05/serverless-with-aws-lambda-scala.html">Lambda</a> and its more recent <a target="_blank" href="http://automateddeveloper.blogspot.com/2018/10/machine-learning-with-aws-scala.html">Machine Learning capabilities</a>.<br/><br/>
#   <strong>Web Development</strong>: Through building web applications, I have also worked with various client side technology, having used jQuery, Bootstrap, LESS, SASS, Backbone/Underscore/Require. More recently I have written React applications (primarily using the Create React App framework, and extending them)<br/><br/>
#   <strong>Development Control</strong>: I have a good knowledge of application life-cycle management and have worked with SVN, Git, Maven, Gradle, Sonar, Jenkins, TeamCity, etc. I have experience with an array of testing tools and technologies.<br/><br/>
#   I have also gained experience and knowledge of other technologies from several side projects and research that I have undertaken in my free time, including Android, a variety of social APIs (Twitter etc) and cloud platforms such as CloudFoundry/OpenShift/AppFog/AWS. <br/><br/>
#   As part of Nerdability, I created, and am now primary contributor to, two Spring projects - <a target='_blank' href="https://github.com/robhinds/spring-social-geeklist">Spring-Social-Geeklist</a> and <a target='_blank' href="https://github.com/nerdability/spring-social-khan-academy">Spring-Social-Khan-Academy</a>, which provide core integration with those third-party APIs on top of the Spring Social framework. They are both listed as community projects: <a target='_blank' href="http://projects.spring.io/spring-social/">http://projects.spring.io/spring-social/</a>. <br/><br/>
#   I write a blog covering technical and opinion articles that can be found here: <a target='_blank' href="http://automateddeveloper.blogspot.com/">automateddeveloper.blogspot.com</a> (I am also a <a target='_blank' href="https://dzone.com/users/899489/rhinds.html">DZone MVB</a>)
